### ISSUE TITLE
BulkAction : General error: 20018 A column has been specified more than once in the order by list.

### ISSUE THREAD

**Issue by nafil161** [rappasoft/laravel-livewire-tables#1150]
When I click on 'select all' when performing a bulk action on a sorted list of items, encountered a fatal error with the message : 

SQLSTATE[HY000]: General error: 20018 A column has been specified more than once in the order by list. Columns in the order by list must be unique. 

![image](https://user-images.githubusercontent.com/25418429/230759413-31ffb18f-6652-4d40-a001-bb8967b1e7f7.png)

as I can see when I click on the select All the query is duplicating my column select and adding the order by with duplicate.

![image](https://user-images.githubusercontent.com/25418429/230759555-1f7d24f6-1e53-44b7-aeb7-1fc1bf612bf0.png)

Rappasoft Datatable View
![image](https://user-images.githubusercontent.com/25418429/230759731-94f37d9f-49ef-4ced-a375-ef54a3f9a422.png)

**Comment by lrljoe** [comment]
Can you paste your Component code in please, wrap it in code marks so the formatting carries over.
I'll take a look.

Can you confirm which version you are using too please

**Comment by nafil161** [comment]
`<?php

namespace App\Http\Livewire\User\Vendor;

use App\Models\User\UserVendor;
use App\Http\Livewire\Component\DataTableComponent;
use App\Models\User\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Rappasoft\LaravelLivewireTables\Views\Column;

class Table extends DataTableComponent
{
    use AuthorizesRequests;

    public User $user;

    public function configure(): void
    {
        $this->setPrimaryKey('id');
        $this->setPerPageAccepted([25, 50, 100]);
        $this->setTableAttributes([
            'class' => 'table table-bordered',
        ]);
        $this->setSearchDebounce(500);
        $this->setHideBulkActionsWhenEmptyStatus(true);
    }

    public function boot(): void
    {
        $this->authorize('viewAny', User::class);
    }

    public function columns(): array
    {
        return [
            Column::make('ID', 'id')
                ->sortable()->excludeFromColumnSelect()
                ->hideIf(true),
            Column::make('User Id')
                ->sortable()->excludeFromColumnSelect()
                ->hideIf(true),
            Column::make('Name')
                ->sortable()->excludeFromColumnSelect()
                ->format(function ($value, $row) {
                    return '<a href="' . route('user.vendor.show', ['user' => $row->user_id, 'userVendor' => $row->id]) . '" class="text-info text-decoration-underline">' . $value . '</a>';
                })->html(),
            Column::make('Contact')
                ->sortable(),
            Column::make('Phone No', 'phone_no')
                ->sortable(),
            Column::make('Description')
                ->sortable(),
            Column::make('Status')
                ->sortable()
                ->format(function ($value, $row) {
                    return '<span class="badge bg-'.$row->statusClass($value).'">'.
                    $row->statuses($value)
                    .'</span>';
                })->html(),
        ];
    }

    public function builder(): Builder
    {
        return UserVendor::query()
            ->where('user_id', $this->user->id);
    }

    //Bulk Update
    public function bulkActions(): array
    {
        return [
            'bulkUpdate' => 'Bulk Update',
        ];
    }

    public function bulkUpdate()
    {
        $this->emit('bulkUpdate', $this->selected);
    }
}`

**Comment by nafil161** [comment]
Rappasoft version
"rappasoft/laravel-livewire-tables": "^2.7.0",

**Comment by lrljoe** [comment]
In your composer.lock file, what version is actually installed?

Also please can you confirm 

Your alpinejs version (available in package.lock if installed locally)

Whether you're using tailwind or bootstrap, and which version (I e.Tailwind 2, Tailwind 3, Bootstrap 4 or Bootstrap 5)

With that info I should be able to replicate the issue and get it sorted.

**Comment by nafil161** [comment]
1. In your composer.lock file, what version is actually installed? 2.7.0
2. Your alpinejs version (available in package.lock if installed locally) ? Package.lock not exist
3. Whether you're using tailwind or bootstrap, and which version (I e.Tailwind 2, Tailwind 3, Bootstrap 4 or Bootstrap 5) ? Bootstrap 5

**Comment by lrljoe** [comment]
I believe but am not certain that this was fixed in 2.9.0 where there were some sorting and pagination amends

If you have a dev environment then it may be worthwhile updating to the latest release to see how you go.

I'm not seeing the issue in my demo environment, but I'll do some more fiddling to see if I can replicate it.

**Comment by nafil161** [comment]
ok, thanks for the response. I will check with the latest version.

1. For Alpine, have you included Alpine 3.0+ in your HTML? Yes, alpine is at 3.15.
2.  Are you using the latest version of Bootstrap 5? bootstrap@5.0.1

**Comment by lrljoe** [comment]
Please can I recommend you update to BS 5.3.

Also, not sure how you're on Alpine 3.15 when the latest version is 3.12, can you double check that for me please?

Let me know if the upgrades fix everything!

**Comment by nafil161** [comment]
Sorry Alpine was 2x and upgraded to 3x

I am still facing the issue after upgrades.

**Comment by lrljoe** [comment]
I've tried replicating, but not having much luck so far.

Are you now on 
rappasoft/laravel-livewire-tables 2.12
